-- 003: Row Level Security — defense in depth
--
-- The backend connects with the service-role key, which bypasses RLS by
-- design; tenant isolation is enforced at the API layer. These policies
-- exist so that a regression (a route missing its owner check, an anon-key
-- client, a leaked publishable key) can NEVER read another tenant's data
-- directly from Postgres/Storage.
--
-- Model:
--   * No policies for anon/authenticated roles on app tables => deny-all
--     for everything except a user reading rows they own.
--   * service_role keeps full access (implicit bypass).
--
-- Apply order: after 000-002.

-- ─────────────────────────────────────────────────────────────
-- App tables: owner-scoped SELECT only for normal authed users.
-- Writes go through the backend (service role) exclusively.
-- ─────────────────────────────────────────────────────────────
alter table assets     enable row level security;
alter table scans      enable row level security;
alter table violations enable row level security;
alter table reports    enable row level security;

create policy "users read own assets"
  on assets for select to authenticated
  using (owner::text = auth.uid()::text);

create policy "users read scans of own assets"
  on scans for select to authenticated
  using (exists (
    select 1 from assets a where a.asset_id::text = scans.asset_id::text and a.owner::text = auth.uid()::text
  ));

create policy "users read violations of own assets"
  on violations for select to authenticated
  using (exists (
    select 1 from assets a where a.asset_id::text = violations.asset_id::text and a.owner::text = auth.uid()::text
  ));

create policy "users read reports of own assets"
  on reports for select to authenticated
  using (exists (
    select 1 from assets a where a.asset_id::text = reports.asset_id::text and a.owner::text = auth.uid()::text
  ));

-- ─────────────────────────────────────────────────────────────
-- Vector stores: no client-facing reads at all (backend-only).
-- ─────────────────────────────────────────────────────────────
alter table asset_embeddings enable row level security;
alter table rag_documents    enable row level security;
-- No policies created => authenticated/anon roles get nothing.

-- ─────────────────────────────────────────────────────────────
-- Storage: the 'assets' bucket is private (002) and we deliberately
-- create NO storage policies => deny-all for anon/authenticated roles.
-- Clients access media only via short-lived signed URLs generated by the
-- backend (service-role bypasses RLS to create them).
-- ─────────────────────────────────────────────────────────────
